import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { Playfair_Display } from "next/font/google";
import "./globals.css";

const fontNormal = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const fontTitle = Playfair_Display({
  variable: "--font-playfair",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export { fontNormal, fontTitle };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
{
  return (
    <html lang="en">
      <body
        className={`${fontNormal.variable} ${fontTitle.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
